spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_energy?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  # redis
  redis:
    host: 192.168.2.88
    password: Redis_kmzx@1234

custom:
  attachmentServer: http://127.0.0.1/static
  attachmentPath: C:/var/www/html
  attachmentGainPath: C:/var/www/html/upload
  attachmentTempPath: C:/var/www/html/upload/temp