spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/new_energy?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    password: Redis_kmzx@1234

custom:
  # 附件地址
  attachmentServer: http://www.zhwlt.cn/static
  attachmentPath: /var/www/html
  attachmentGainPath: /var/www/html/upload
  attachmentTempPath: /var/www/html/upload/temp